### ISSUE TITLE
npm link fails

### ISSUE THREAD

**Issue by lorensr** [benawad/apollo-mocked-provider#34]
My test that was working when using the registry version of `apollo-mocked-provider@4.0.1` now fails after `npm link` in a local copy of this repo (both on latest master and b4e22ef) and `npm link apollo-mocked-provider` in my app.

```
    console.error node_modules/react-dom/cjs/react-dom.development.js:19527
      The above error occurred in the <_default> component:
          in _default (at TableOfContents.test.js:8)
          in ApolloProvider
          in Unknown (at setupTests.js:37)
          in Router (at setupTests.js:26)
          in RouterWrapper (at setupTests.js:36)
          in MockedWrapper
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● TableOfContents › should render loading and chapters

    Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or 
pass an ApolloClient instance in via options.

      36 | 
      37 | export default () => {
    > 38 |   const { data: { chapters } = {}, loading } = useQuery(CHAPTER_QUERY)
         |                                                ^
      39 |   const client = useApolloClient()
      40 | 
      41 |   return (

      at new InvariantError (node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.esm.js:12:28)
      at Object.invariant (node_modules/@apollo/client/node_modules/ts-invariant/lib/invariant.esm.js:24:15)
      at QueryData.Object.<anonymous>.OperationData.refreshClient (node_modules/@apollo/client/react/data/OperationData.js:29:75)
      at QueryData.Object.<anonymous>.QueryData.execute (node_modules/@apollo/client/react/data/QueryData.js:87:14)
      at node_modules/@apollo/client/react/hooks/utils/useBaseQuery.js:35:95
      at useDeepMemo (node_modules/@apollo/client/react/hooks/utils/useDeepMemo.js:6:42)
      at useBaseQuery (node_modules/@apollo/client/react/hooks/utils/useBaseQuery.js:35:18)
      at useQuery (node_modules/@apollo/client/react/hooks/useQuery.js:3:12)
      at _default (src/components/TableOfContents.js:38:48)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14803:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17482:13)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:18596:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:237:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:292:31)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23203:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22157:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22130:22)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:21756:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21188:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:24373:3)
      at node_modules/react-dom/cjs/react-dom.development.js:24758:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:21903:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:24757:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:24840:10)
      at node_modules/@testing-library/react/dist/pure.js:99:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:21856:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:929:14)
      at render (node_modules/@testing-library/react/dist/pure.js:95:26)
      at mockedRender (src/setupTests.js:51:10)
      at Object.it (src/components/TableOfContents.test.js:8:5)


Test Suites: 1 failed, 1 skipped, 1 of 2 total
```

**Comment by lorensr** [comment]
@benawad since I'm failing at using the latest master locally, would you mind cutting a release? 😄

**Comment by benawad** [comment]
should auto-deploy on merge, I can trigger a release tho

**Comment by lorensr** [comment]
Thanks, that would be great. Looks like the `Add defaultOptions option to createApolloMockedProvider` commit should have had a `BREAKING` message in it according to https://github.com/semantic-release/semantic-release#how-does-it-work

![image](https://user-images.githubusercontent.com/251288/101707380-1a240280-3a59-11eb-93d5-330e38e53ddc.png)
